export interface PersonKomForWaechter {
id: number; // [Id] [int] IDENTITY(1,1) NOT NULL,
//   personId: number; // [PersonId] [int] NOT NULL,
personName: string; // [PersonName] [nvarchar](255) NULL,
komArt: string; // [KomArt] [nvarchar](255) NULL,
//   vorwahl: string; // [Vorwahl] [nvarchar](255) NULL,
nummer: string; // [Nummer] [nvarchar](255) NULL,
//   land: string; // [Land] [nvarchar](255) NULL,
//   versuche: number; // [Versuche] [int] NULL,
//   anforderung: Date; // [Anforderung] [datetime] NULL,
//   reaktion: string; // [Reaktion] [nvarchar](255) NULL,
//   reaktionDatum: Date; // [ReaktionDatum] [datetime] NULL,
//   bemerkung: string; // [Bemerkung] [nvarchar](200) NULL,
//   status: number; // [Status] [int] NULL,
//   val1: number; // [Val1] [int] NULL,
//   val2: number; // [Val2] [int] NULL,
//   val3: boolean; // [Val3] [bit] NULL,
//   val4: boolean; // [Val4] [bit] NULL,
//   val5: string; // [Val5] [nvarchar](255) NULL,
//   val6: string; // [Val6] [nvarchar](255) NULL,
//   addDate: Date; // [AddDate] [datetime] NULL,
//   addUser: string; // [AddUser] [nvarchar](50) NULL,
//   changeDate: Date; // [ChangeDate] [datetime] NULL,
//   changeUser: string; // [ChangeUser] [nvarchar](450) NULL,
//   owner: string; // [Owner] [nvarchar](450) NULL,
}
