export interface QuickViewWaechter {
  id: number | undefined;
  kalender: number | undefined;
  display: string | undefined;
  kategorie1: string | undefined;
  kategorie2: string | undefined;
  text: string | undefined;
  firstEvent: string | undefined;
  wiederholung: number | undefined;
  startDate: Date | undefined;
  eventDate: Date | undefined;
  status: number | undefined;
  erinnerung: number | undefined;
  anzahlPersonKom: number | undefined;
  erinnerungen: number | undefined;
  gesamtErinnerungen: number | undefined;
  outErinnerungen: number | undefined;
  restErinnerungen: number | undefined;
}
